name: Build-PhysX-4.1
on:
  workflow_dispatch:

jobs:
  Build-PhysX-MacOS-Checked:
    runs-on: macos-12
    steps:
      
      - name: Clone PhysX 4.1
        run: git clone -b 4.1 https://github.com/NVIDIAGameWorks/PhysX
      
      # Added: -Wno-alloca and -Wno-anon-enum-enum-conversion
      - name: Copy fixed CMakeLists
        run: git clone https://github.com/bloeys/physx-builder && cp ./physx-builder/macCMakeLists.txt ./PhysX/physx/source/compiler/cmake/mac/CMakeLists.txt

      - name: Disable building snippets
        run: cp ./physx-builder/mac64.xml ./PhysX/physx/buildtools/presets/public/mac64.xml
      
      - name: Generate xcode project
        working-directory: ./PhysX/physx
        run: ./generate_projects.sh mac64 # 'mac64' is from the buildtools/presets folder
      
      - name: Build PhysX Checked
        working-directory: ./PhysX/physx/compiler/mac64
        run: xcodebuild -project PhysXSDK.xcodeproj -alltargets -configuration checked
      
      - name: Upload Checked artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: physx-libs-macos-x64-checked
          path: ./PhysX/physx/bin/mac.x86_64/checked/

      - name: Build PhysX Release
        working-directory: ./PhysX/physx/compiler/mac64
        run: xcodebuild -project PhysXSDK.xcodeproj -alltargets -configuration release

      - name: Upload Release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: physx-libs-macos-x64-release
          path: ./PhysX/physx/bin/mac.x86_64/release/
