name: Build-PhysX-4.1
on:
  workflow_dispatch:

jobs:
  Build-PhysX-MacOS:
    runs-on: macos-10.15
    steps:
      - name: Clone PhysX 4.1
        run: git clone -b 4.1 https://github.com/NVIDIAGameWorks/PhysX
      - name: Inject bug fix into cmake
        #Added: -Wno-alloca
        run: echo 'SET(PHYSX_CXX_FLAGS "${OSX_BITNESS} -msse2 -std=c++11 -fno-rtti -fno-exceptions -ffunction-sections -fdata-sections -Wno-alloca -Werror -ferror-limit=0 -Wall -Wextra -fstrict-aliasing -Wstrict-aliasing=2 -Weverything -Wno-unknown-warning-option -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command -Wno-float-equal -Wno-padded -Wno-weak-vtables -Wno-cast-align -Wno-conversion -Wno-missing-noreturn -Wno-missing-variable-declarations -Wno-shift-sign-overflow -Wno-covered-switch-default -Wno-exit-time-destructors -Wno-global-constructors -Wno-missing-prototypes -Wno-unreachable-code -Wno-unused-macros -Wno-unused-member-function -Wno-used-but-marked-unused -Wno-weak-template-vtables -Wno-deprecated -Wno-non-virtual-dtor -Wno-invalid-noreturn -Wno-return-type-c-linkage -Wno-reserved-id-macro -Wno-c++98-compat-pedantic -Wno-unused-local-typedef -Wno-old-style-cast -Wno-newline-eof -Wno-unused-private-field -Wno-undefined-reinterpret-cast -Wno-invalid-offsetof -Wno-zero-as-null-pointer-constant -Wno-atomic-implicit-seq-cst -gdwarf-2" CACHE INTERNAL "PhysX CXX")' >> ./PhysX/physx/source/compiler/cmake/mac/CMakeLists.txt
      - name: Check Cmake
        run: cat ./PhysX/physx/source/compiler/cmake/mac/CMakeLists.txt
      - name: Generate xcode project
        working-directory: ./PhysX/physx
        run: echo 1 | ./generate_projects.sh
      - name: Build PhysX Checked
        working-directory: ./PhysX/physx/compiler/mac64
        run: xcodebuild -project PhysXSDK.xcodeproj -alltargets -configuration checked
      - name: Upload libraries to GitHub Actions Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: physx-libs-macos-x64
          path: ./PhysX/physx/bin/mac.x86_64/checked/
